{% set name = "chooch" %}
{% set version = "5.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # No tag for 5.0.9 - there is an old TESTREL-5.1.0
  # but version still hard-coded to 5.0.9 in:
  # - Makefile: https://github.com/fadnywg/chooch/blob/d472b85202e8b30103cb8b72accc97d09e2063f6/Makefile.x86_64#L18
  # - copyright.c: https://github.com/fadnywg/chooch/blob/d472b85202e8b30103cb8b72accc97d09e2063f6/copyright.c#L22
  url: https://github.com/fadnywg/chooch/archive/d472b85202e8b30103cb8b72accc97d09e2063f6.zip
  sha256: 86e561007859ef4a6d596741ea8c3f934030ba43de599d34ed2ebfa158879db5

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - gsl
    - plplot
    - libblas

test:
  source_files:
    - examples/Cutest.raw
  commands:
    - chooch -e Cu -a K examples/Cutest.raw

about:
  home: https://github.com/fadnywg/chooch
  summary: 'A program for calculating anomalous scattering factors from X-ray fluorescence spectra'
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  dev_url: https://github.com/fadnywg/chooch

extra:
  recipe-maintainers:
    - beenje
